#!/bin/bash
# Installs qube and qube-menu, the Omarchy menu rows, and the Hyprland hook that
# loads the generated border rules. The bar widget is added from the Omarchy
# plugin UI, or with `omarchy plugin add <this repo's URL> --enable`.
#
# Safe to re-run: the menu block and the Hyprland hook are replaced in place,
# never duplicated.

set -euo pipefail

REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
BIN_DIR="$HOME/.local/bin"
MENU="$HOME/.config/omarchy/extensions/omarchy-menu.jsonc"
HYPR="$HOME/.config/hypr/hyprland.lua"
BEGIN="// >>> omarchy-qubes"
END="// <<< omarchy-qubes"

mkdir -p "$BIN_DIR"
for script in qube qube-menu; do
  ln -sf "$REPO/bin/$script" "$BIN_DIR/$script"
  echo "linked $BIN_DIR/$script -> $REPO/bin/$script"
done

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note: $BIN_DIR is not on PATH — the menu rows call qube-menu by name" >&2 ;;
esac

# The rows live between two markers, so a re-run swaps the block rather than
# appending a second one. A file without the markers gets the block just
# before its closing brace.
if [[ -f $MENU ]]; then
  cp "$MENU" "$MENU.bak.$(date +%s)"
  python3 - "$MENU" "$REPO/menu.jsonc" "$BEGIN" "$END" <<'EOF'
import re, sys
path, rows_path, begin, end = sys.argv[1:]
text = open(path).read()
rows = open(rows_path).read().rstrip("\n")
block = f"  {begin}\n{rows}\n  {end}\n"
pattern = re.compile(r"[ \t]*" + re.escape(begin) + r".*?" + re.escape(end) + r"\n?", re.S)
if pattern.search(text):
    text = pattern.sub(lambda _: block, text)
else:
    i = text.rstrip().rfind("}")
    text = text[:i].rstrip("\n") + "\n\n" + block + "}\n"
open(path, "w").write(text)
EOF
  echo "menu rows written to $MENU"
else
  echo "note: $MENU not found — skipped the menu rows" >&2
fi

# hyprland.lua loads the rules only when qube has written them, so removing
# the file later never breaks the config.
if [[ -f $HYPR ]] && ! grep -q 'require("hypr.qubes")' "$HYPR"; then
  cp "$HYPR" "$HYPR.bak.$(date +%s)"
  cat >>"$HYPR" <<'EOF'

-- Border colours for qube windows, generated by `qube`.
local qubes_rules = io.open(os.getenv("HOME") .. "/.config/hypr/qubes.lua")
if qubes_rules then
  qubes_rules:close()
  require("hypr.qubes")
end
EOF
  echo "hooked qube border rules into $HYPR"
fi
"$REPO/bin/qube" rules

missing=()
for cmd in qemu-system-x86_64 qemu-img waypipe socat jq; do
  command -v "$cmd" >/dev/null || missing+=("$cmd")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo
  echo "still missing: ${missing[*]}"
  echo "    omarchy pkg add qemu-base waypipe socat jq"
fi

cat <<'NOTE'

Next:

    qube template create           # one-off: Arch plus waypipe, foot, Firefox
    qube create work --label blue
    qube run work firefox

Open the menu with Super+Space and type "qubes", or bind a key to:

    omarchy menu summon qubes

NOTE
